
defaults:
  - _self_
  - optimizer: Adam.yaml
  # - scheduler: cyclic.yaml
  - model: Baseline.yaml
  - experiments: base_expe.yaml

test: test
task_name: debug

loss: BCELoss
metric: Accuracy
num_epochs: 100
patience: 10

num_workers: 2
batch_size: 128
name_out_submit: output 


cache: True

transform:
  transform_name: basic
  resolution: 98
